MVCTodoList/Models/TodoListsCollection.cs
using System.Collections.Generic;

namespace MVCTodoList.Models
{
    public class TodoListsCollection
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public ApplicationUser ApplicationUser { get; set; }
        public List<TodoList> Items { get; set; }

        public TodoListsCollection()
        {
            Items = new List<TodoList>();
        }
    }
}

MVCTodoList/Controllers/TodoListsCollectionController.cs
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using MVCTodoList.Models;

namespace MVCTodoList.Controllers
{
    [Authorize]
    public class TodoListsCollectionController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();

            var model = db.TodoListsCollections
                .Where(c => c.ApplicationUser.Id == userId)
                .Include(c => c.Items.Select(i => i.Items));

            return View(model);
        }

        public ActionResult Detail(int collectionId)
        {
            var userId = User.Identity.GetUserId();

            var model = db.TodoListsCollections
                .Where(c => c.ApplicationUser.Id == userId && c.Id == collectionId)
                .Include(c => c.Items.Select(i => i.Items))
                .FirstOrDefault();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCollection(string name)
        {
            if (ModelState.IsValid)
            {
                var user = db.Users.Find(User.Identity.GetUserId());

                db.TodoListsCollections.Add(new TodoListsCollection { Name = name, ApplicationUser = user });
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        public ActionResult DeleteCollection(int collectionId)
        {
            var collection = db.TodoListsCollections.Find(collectionId);
            if (collection == null)
            {
                return HttpNotFound();
            }

            db.TodoListsCollections.Remove(collection);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateList(int collectionId, string name)
        {
            if (ModelState.IsValid)
            {
                var collection = db.TodoListsCollections.Find(collectionId);
                db.TodoLists.Add(new TodoList { TodoListsCollection = collection, Name = name });
                db.SaveChanges();

                return RedirectToAction("Detail", new { collectionId });
            }

            return RedirectToAction("Detail", new { collectionId });
        }

        public ActionResult DeleteList(int collectionId, int listId)
        {
            var list = db.TodoLists.Find(listId);
            if (list == null)
            {
                return HttpNotFound();
            }

            db.TodoLists.Remove(list);
            db.SaveChanges();

            return RedirectToAction("Detail", new { collectionId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateItem(int collectionId, int listId, string name)
        {
            var todoList = db.TodoLists.Find(listId);
            if (ModelState.IsValid)
            {
                db.TodoListItems.Add(new TodoListItem { TodoList = todoList, Name = name });
                db.SaveChanges();

                return RedirectToAction("Detail", new { collectionId });
            }

            return RedirectToAction("Detail", new { collectionId });
        }

        public ActionResult DeleteItem(int collectionId, int listId, int itemId)
        {
            var listItem = db.TodoListItems.Find(itemId);
            if (listItem == null)
            {
                return HttpNotFound();
            }

            db.TodoListItems.Remove(listItem);
            db.SaveChanges();

            return RedirectToAction("Detail", new { collectionId });
        }

        #region Async Actions

        public ActionResult CreateCollectionAsync(string name)
        {
            if (ModelState.IsValid)
            {
                var user = db.Users.Find(User.Identity.GetUserId());

                var newCollection = new TodoListsCollection { Name = name, ApplicationUser = user };
                db.TodoListsCollections.Add(newCollection);
                db.SaveChanges();

                return PartialView("_CollectionView", newCollection);
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        public ActionResult DeleteCollectionAsync(int collectionId)
        {
            var collection = db.TodoListsCollections.Find(collectionId);
            if (collection == null)
            {
                return HttpNotFound();
            }

            db.TodoListsCollections.Remove(collection);
            db.SaveChanges();

            return new EmptyResult();
        }

        public ActionResult CreateListAsync(int collectionId, string name)
        {
            if (ModelState.IsValid)
            {
                var todoListCollection = db.TodoListsCollections.Find(collectionId);
                var newList = new TodoList { TodoListsCollection = todoListCollection, Name = name };
                db.TodoLists.Add(newList);
                db.SaveChanges();

                return PartialView("_ListView", newList);
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        public ActionResult DeleteListAsync(int collectionId, int listId)
        {
            var list = db.TodoLists.Find(listId);
            if (list == null)
            {
                return HttpNotFound();
            }

            db.TodoLists.Remove(list);
            db.SaveChanges();

            return new EmptyResult();
        }
        
        public ActionResult CreateItemAsync(int collectionId, int listId, string name)
        {
            if (ModelState.IsValid)
            {
                var todoList = db.TodoLists.Find(listId);
                var newItem = new TodoListItem { TodoList = todoList, Name = name };
                db.TodoListItems.Add(newItem);
                db.SaveChanges();

                return PartialView("_ItemView", newItem);
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        public ActionResult DeleteItemAsync(int collectionId, int listId, int itemId)
        {
            var listItem = db.TodoListItems.Find(itemId);
            if (listItem == null)
            {
                return HttpNotFound();
            }

            db.TodoListItems.Remove(listItem);
            db.SaveChanges();

            return new EmptyResult();
        }

        #endregion

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCTodoList/Views/TodoListsCollection/Detail.cshtml
@model MVCTodoList.Models.TodoListsCollection

@{
    ViewBag.Title = $"{Model.Name}";
}

@Html.Partial("_CollectionDetails", Model)

MVCTodoList/Views/TodoListsCollection/Index.cshtml
@model IEnumerable<MVCTodoList.Models.TodoListsCollection>

@{
    ViewBag.Title = "Index";
}

<h1>Collections</h1>
<div class="row">
    @foreach (var todoListCollection in Model)
    {
        @Html.Partial("_CollectionView", todoListCollection)
    }

    <span id="collections"></span>

    <div class="col-sm-4">
        <div class="collection-view">
            @using (Html.BeginForm("CreateCollection", "TodoListsCollection", FormMethod.Post))
            {
                @Html.AntiForgeryToken()

                <h4>Create new collection</h4>
                <div class="input-group">
                    <input id="name" type="text" name="name" value="" class="form-control" placeholder="New collection name" />
                    <span class="input-group-btn">
                        <input type="submit" value="Create collection" class="btn btn-default" />
                    </span>
                </div>
            }

            @using (Ajax.BeginForm("CreateCollectionAsync", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = $"collections", InsertionMode = InsertionMode.InsertAfter }))
            {
                @Html.AntiForgeryToken()

                <h4>Create new collection async</h4>
                <div class="input-group">
                    <input id="name" type="text" name="name" value="" class="form-control" placeholder="New collection name" />
                    <span class="input-group-btn">
                        <input type="submit" value="Create collection async" class="btn btn-default" />
                    </span>
                </div>
            }
        </div>
    </div>
</div>

MVCTodoList/Views/TodoListsCollection/_CollectionDetails.cshtml
@model MVCTodoList.Models.TodoListsCollection

<h2 class="list-title">@Model.Name</h2>
<div id="" class="lists">
    @foreach (var todoList in Model.Items)
    {
        @Html.Partial("_ListView", todoList)
    }

    <span id="collection-content"></span>

    <div class="add-list-form">
        @using (Html.BeginForm("CreateList", "TodoListsCollection", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <h4>Create new list</h4>
            <div class="input-group">
                <input id="collectionId" type="hidden" name="collectionId" value="@Model.Id" />
                <input id="name" type="text" name="name" value="" class="form-control" placeholder="New list name" />
                <span class="input-group-btn">
                    <input type="submit" value="Create list" class="btn btn-default" />
                </span>
            </div>
        }

        <br/>

        @using (Ajax.BeginForm("CreateListAsync", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = $"collection-content", InsertionMode = InsertionMode.InsertAfter }))
        {
            @Html.AntiForgeryToken()

            <h4>Create new list async</h4>
            <div class="input-group">
                <input id="collectionId" type="hidden" name="collectionId" value="@Model.Id" />
                <input id="name" type="text" name="name" value="" class="form-control" placeholder="New list name" />
                <span class="input-group-btn">
                    <input type="submit" value="Create list async" class="btn btn-default" />
                </span>
            </div>
        }
    </div>
</div>

MVCTodoList/Views/TodoListsCollection/_CollectionView.cshtml
@model MVCTodoList.Models.TodoListsCollection

<div id="collection-@Model.Id" class="col-sm-4">
    <div class="collection-view">
        <a href=@Url.Action("Detail", new { collectionId = Model.Id }) class="btn btn-primary">

            @Model.Name
            <a style="font-size: 16px;" href="@Url.Action("DeleteCollection", new { collectionId = Model.Id})" class="pull-right margin-top-5">
                <span class="glyphicon glyphicon-trash" title="Delete"></span>
            </a>

            @Ajax.ActionLink("Delete Async", "DeleteCollectionAsync", new { collectionId = Model.Id }, new AjaxOptions
            {
                HttpMethod = "POST",
                UpdateTargetId = $"collection-{Model.Id}",
                InsertionMode = InsertionMode.ReplaceWith,
            }, new { @class = "pull-right margin-top-5" })
        </a>
    </div>
</div>

MVCTodoList/Views/TodoListsCollection/_ItemView.cshtml
@model MVCTodoList.Models.TodoListItem

<div id="list-item-@Model.Id" class="list-item">
    <h5>@Html.DisplayFor(Model => Model.Name)</h5>
    <a href="@Url.Action("DeleteItem", new { collectionId = Request.Params["collectionId"], listId = Model.TodoList.Id, itemId = Model.Id  })" class="btn btn-danger">
        <span class="glyphicon glyphicon-trash"></span>
        Delete
    </a>

    @Ajax.ActionLink("Delete Async", "DeleteItemAsync", new { collectionId = Request.Params["collectionId"], listId = Model.TodoList.Id, itemId = Model.Id }, new AjaxOptions
    {
        HttpMethod = "POST",
        UpdateTargetId = $"list-item-{Model.Id}",
        InsertionMode = InsertionMode.ReplaceWith,
    })
</div>

MVCTodoList/Views/TodoListsCollection/_ListView.cshtml
@model MVCTodoList.Models.TodoList

<div id="list-@Model.Id" class="list">
    <h4>
        @Model.Name
        <a style="font-size: 16px; margin-top: -20px;" href="@Url.Action("DeleteList", new { collectionId = Model.TodoListsCollection.Id, listId = Model.Id})" class="pull-right">
            <span class="glyphicon glyphicon-trash" title="Delete"></span>
        </a>
        @Ajax.ActionLink("Delete Async", "DeleteListAsync", new { collectionId = Model.TodoListsCollection.Id, listId = Model.Id }, new AjaxOptions
        {
            HttpMethod = "POST",
            UpdateTargetId = $"list-{Model.Id}",
            InsertionMode = InsertionMode.ReplaceWith,
        })
    </h4>

    @foreach (var item in Model.Items)
    {
        @Html.Partial("_ListItemView", item)
    }

    <span id="list-content-@Model.Id"></span>

    @using (Html.BeginForm("CreateItem", "TodoListsCollection", new { collectionId = Model.TodoListsCollection.Id, listId = Model.Id }))
    {
        @Html.AntiForgeryToken()

        <div class="input-group">
            <input id="name" type="text" name="name" value="" class="form-control" placeholder="New item name" />
            <span class="input-group-btn">
                <input type="submit" value="Create" class="btn btn-default" />
            </span>
        </div>
    }

    @using (Ajax.BeginForm("CreateItemAsync", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = $"list-content-{Model.Id}", InsertionMode = InsertionMode.InsertAfter }))
    {
        @Html.AntiForgeryToken()

        <div class="input-group">
            <input id="collectionId" type="hidden" name="collectionid" value="@Model.TodoListsCollection.Id" />
            <input id="listId" type="hidden" name="listId" value="@Model.Id" />
            <input id="name" type="text" name="name" value="" class="form-control" placeholder="New item name" />
            <span class="input-group-btn">
                <input type="submit" value="Create Async" class="btn btn-default" />
            </span>
        </div>
    }
</div>